language: java
if: branch = master

git:
  depth: 1

script:
  - git add -A -v
  - git commit -m "Add auto-built files."

deploy:
  provider: pages
  skip_cleanup: false
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: false
