language: generic
if: branch = master

git:
  depth: 1

deploy:
  provider: pages
  skip_cleanup: false
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: false
